scripts/helm/app/alerts.yaml
scripts/helm/app/assets.yaml
scripts/helm/app/chalice.yaml
scripts/helm/app/db.yaml
scripts/helm/app/ender.yaml
scripts/helm/app/http.yaml
scripts/helm/app/integrations.yaml
scripts/helm/app/sink.yaml
scripts/helm/app/storage.yaml
scripts/helm/kube-install.sh
scripts/helm/nginx-ingress/nginx-ingress/templates/configmap.yaml
scripts/helm/nginx-ingress/nginx-ingress/values.yaml
scripts/helm/roles/openreplay/tasks/install-apps.yaml
scripts/helm/roles/openreplay/tasks/pre-check.yaml
scripts/helm/roles/openreplay/templates/monitoring.yaml
scripts/helm/vars.yaml

Can access monitoring dashboards with
https://domain_name/grafana

Enable monitoring for enterprise edition

---

scripts/helm/roles/openreplay/defaults/main.yaml

Signed-off-by: Rajesh Rajendran <rjshrjndrn@gmail.com>

fix(ansible): initialize nil value

---

scripts/helm/roles/openreplay/tasks/install-dbs.yaml

Ansible task fix to download to specific path
Signed-off-by: Rajesh Rajendran <rjshrjndrn@gmail.com>

fix(install): init frontend

---

api/chalicelib/core/sessions.py
api/db_changes.sql
ee/scripts/helm/db/init_dbs/postgresql/1.3.0/1.3.0.sql
ee/scripts/helm/db/init_dbs/postgresql/init_schema.sql
scripts/helm/app/chalice.yaml
scripts/helm/db/init_dbs/postgresql/1.3.0/1.3.0.sql
scripts/helm/db/init_dbs/postgresql/init_schema.sql

super accelerated sessions search 🤞🤞

Api lateral join search

---

api/chalicelib/blueprints/bp_core_dynamic.py

* feat(api): include smtp flag in login response
* feat(api): changed smtp flag in login response
* feat(api): owner role is not allowed to change
* feat(api): changed chalice template
* feat(api): reset password invitation|token

Api changes (#124)

---

api/chalicelib/core/users.py

* feat(api): include smtp flag in login response
* feat(api): changed smtp flag in login response
* feat(api): owner role is not allowed to change
* feat(api): changed chalice template
* feat(api): reset password invitation|token
* feat(api): fixed invitation token

Api changes (#126)

---

api/chalicelib/core/users.py
ee/api/chalicelib/core/users.py

* feat(api): include smtp flag in login response
* feat(api): changed smtp flag in login response
* feat(api): owner role is not allowed to change
* feat(api): changed chalice template
* feat(api): reset password invitation|token
* feat(api): fixed invitation token
* feat(api): after invitation return identical result
* feat(api): remove password when user deleted
* feat(api): fix login on password change

Api changes (#131)

---

api/chalicelib/utils/s3.py
scripts/helm/openreplay-cli

v1.3.0 hotfix

---

api/chalicelib/core/sourcemaps_parser.py
utilities/servers/sourcemaps-handler.js

feat(utilities): use shared S3 config

Share S3 config between chalice and utilities

---

api/requirements.txt
ee/api/requirements.txt
utilities/package-lock.json
utilities/package.json

feat(utilities): dependencies upgrade

feat(api): dependencies upgrade

---

scripts/helm/roles/openreplay/tasks/install-dbs.yaml

fix: remove duplicated yaml configuration

---

tracker/tracker-assist/README.md

Purpose
--
fix typo in tracker-assis's readme

docs: fix typo in tracker-assist's README

---

api/chalicelib/core/sessions.py
api/routers/core.py

feat(api): ignore FETCH filter if all filters not applied

Chore (release): Fix db issue for v1.5.3

---

frontend/app/components/BugFinder/SessionsMenu/SessionsMenu.js
frontend/app/components/shared/Filters/FilterModal/FilterModal.tsx
frontend/app/components/shared/Filters/FilterModal/index.ts
frontend/app/components/shared/Filters/LiveFilterModal/LiveFilterModal.tsx
frontend/app/components/shared/MainSearchBar/MainSearchBar.tsx
frontend/app/components/shared/MainSearchBar/mainSearchBar.css
frontend/app/components/shared/SaveSearchModal/SaveSearchModal.tsx
frontend/app/components/shared/SavedSearch/SavedSearch.tsx
frontend/app/components/shared/SavedSearch/components/SavedSearchModal/SavedSearchModal.tsx
frontend/app/components/shared/SavedSearch/components/SavedSearchModal/index.ts
frontend/app/components/shared/SavedSearch/components/SavedSearchModal/savedSearchModal.css
frontend/app/components/shared/SessionSettings/components/CaptureRate.tsx
frontend/app/components/shared/SessionSettings/components/DefaultPlaying.tsx
frontend/app/components/shared/SessionSettings/components/DefaultTimezone.tsx
frontend/app/components/shared/SessionSettings/components/ListingVisibility.tsx
frontend/app/components/ui/CountryFlag/CountryFlag.js
frontend/app/components/ui/Toggler/toggler.css
frontend/app/types/ts/search.ts

- search bar now can filter categories and filters
- country flag component don't show popup now
- fixed toggle head bg
- success/error notifications for session settings updates
- small fixes like renaming "manage" to "session settings" + adding a bg to this button
- new session search modal

UI bug fixes 2

---

frontend/app/components/Dashboard/NewDashboard.tsx
frontend/app/components/Dashboard/Widgets/CallWithErrors/CallWithErrors.js
frontend/app/components/Dashboard/Widgets/CustomMetricsWidgets/CustomMetricTable/CustomMetricTable.tsx
frontend/app/components/Dashboard/Widgets/CustomMetricsWidgets/CustomMetricWidget/CustomMetricWidget.tsx
frontend/app/components/Dashboard/Widgets/MissingResources/MissingResources.js
frontend/app/components/Dashboard/Widgets/MostImpactfulErrors/MostImpactfulErrors.js
frontend/app/components/Dashboard/Widgets/PredefinedWidgets/CallWithErrors/CallWithErrors.tsx
frontend/app/components/Dashboard/Widgets/PredefinedWidgets/MissingResources/MissingResources.tsx
frontend/app/components/Dashboard/Widgets/PredefinedWidgets/SlowestResources/SlowestResources.tsx
frontend/app/components/Dashboard/Widgets/SlowestImages/SlowestImages.js
frontend/app/components/Dashboard/Widgets/SlowestResources/SlowestResources.js
frontend/app/components/Dashboard/Widgets/common/Table.js
frontend/app/components/Dashboard/components/DashboardEditModal/DashboardEditModal.tsx
frontend/app/components/Dashboard/components/DashboardForm/DashboardForm.tsx
frontend/app/components/Dashboard/components/DashboardMetricSelection/DashboardMetricSelection.tsx
frontend/app/components/Dashboard/components/DashboardModal/DashboardModal.tsx
frontend/app/components/Dashboard/components/DashboardOptions/DashboardOptions.tsx
frontend/app/components/Dashboard/components/DashboardRouter/DashboardRouter.tsx
frontend/app/components/Dashboard/components/DashboardSideMenu/DashboardSideMenu.tsx
frontend/app/components/Dashboard/components/DashboardView/DashboardView.tsx
frontend/app/components/Dashboard/components/MetricsView/MetricsView.tsx
frontend/app/components/Dashboard/components/WidgetChart/WidgetChart.tsx
frontend/app/components/Dashboard/components/WidgetPredefinedChart/WidgetPredefinedChart.tsx
frontend/app/components/Dashboard/components/WidgetWrapper/TemplateOverlay.tsx
frontend/app/components/Dashboard/components/WidgetWrapper/WidgetWrapper.tsx
frontend/app/components/Dashboard/components/WidgetWrapper/widgetWrapper.css
frontend/app/components/ui/PageTitle/PageTitle.tsx
frontend/app/mstore/dashboardStore.ts

- fix dashboard routing navigation
- fix spelling in multiple places
- fix dashboard state updates
- fix dashboard pinning
- etc

UI dashboard fixes 2

---

frontend/app/components/Dashboard/components/DashboardMetricSelection/DashboardMetricSelection.tsx
frontend/app/components/Dashboard/components/DashboardSideMenu/DashboardSideMenu.tsx
frontend/app/components/ui/ItemMenu/itemMenu.css

- removed additional divider for dashboard side menu
- fixed z-index for "more options" dropdown

UI dashboard fixes 3

---

backend/internal/datasaver/messages.go
backend/internal/handlers/custom/eventMapper.go
backend/pkg/messages/batch.go

Added timestamp for SessionStart and moved RawErrorEvent to db datasaver (right now we can miss RawErrorEvent because if zero timestamp)

Message timestamp changes

---

scripts/helmcharts/openreplay/charts/alerts/templates/service.yaml
scripts/helmcharts/openreplay/charts/assets/templates/service.yaml
scripts/helmcharts/openreplay/charts/chalice/templates/service.yaml
scripts/helmcharts/openreplay/charts/db/templates/service.yaml
scripts/helmcharts/openreplay/charts/heuristics/templates/service.yaml
scripts/helmcharts/openreplay/charts/http/templates/service.yaml
scripts/helmcharts/openreplay/charts/integrations/templates/service.yaml
scripts/helmcharts/openreplay/charts/sink/templates/service.yaml
scripts/helmcharts/openreplay/charts/storage/templates/service.yaml

fix(helm): service port installation issue

---

tracker/tracker/package.json
tracker/tracker/scripts/compile.js
tracker/tracker/src/main/modules/input.ts

Fix for #505 
Added new option to hide date inputs, fixed date recording and reorganized isInput method for better perf

fix(ui): fix tracker date recording, added new obscure dates opt

---

backend/cmd/ender/main.go
backend/internal/config/ender/config.go
backend/internal/db/datasaver/messages.go
backend/internal/http/router/handlers-web.go
backend/pkg/db/cache/messages-common.go
backend/pkg/db/cache/messages-ios.go
backend/pkg/db/cache/messages-web.go
backend/pkg/db/postgres/messages-common.go

moved recording sessionStart to db into http service and sessionEnd into ender service

Session start/end improvements 

---

tracker/tracker/src/main/app/observer/observer.ts
tracker/tracker/src/main/app/sanitizer.ts

feat(ui): add option to skip entire containers and their children tree

---

frontend/app/player/MessageDistributor/MessageDistributor.ts
tracker/tracker/src/common/webworker.ts
tracker/tracker/src/main/app/index.ts
tracker/tracker/src/webworker/BatchWriter.ts
tracker/tracker/src/webworker/index.ts

Related to #538 and other issue, possible fix by adding new "busy" status for worker initialization and additional log options for better debug

fix(tracker): potential fix for writer busy status

---

tracker/tracker/src/main/modules/img.ts

fix(tracker): fix srcset tracking

---

tracker/tracker-assist/src/Assist.ts

This should prevent app from failing when started inside next with dynamic imports settings
Fix for #555

fix(tracker): fix for assist IO imports 

---

backend/Dockerfile
backend/cmd/assets/main.go
backend/go.mod
backend/go.sum
backend/internal/assets/cacher/cacher.go
backend/internal/config/assets/config.go
backend/internal/config/configurator/configurator.go
backend/pkg/env/vars.go

* feat: custom headers
* feat: string map env variable
* fix: status < 400 counts as success 
* chore: `go mod tidy` should be done outside the docker - otherwise it slows down local build

Custom headers for assets cacher requests

---

backend/Dockerfile
backend/cmd/assets/main.go
backend/go.mod
backend/go.sum
backend/internal/assets/cacher/cacher.go
backend/internal/config/assets/config.go
backend/internal/config/configurator/configurator.go
backend/pkg/env/vars.go

* feat: custom headers
* feat: string map env variable
* fix: status < 400 counts as success 
* chore: `go mod tidy` should be done outside the docker - otherwise it slows down local build

Assets cacher: request custom headers

---

api/chalicelib/utils/s3.py
ee/api/chalicelib/core/sessions_favorite_viewed.py

feat(api): refactored s3 helper
feat(api): fixed s3 undefined tagging

v1.7.0 hot fixes 

---

api/chalicelib/core/resources.py
ee/api/chalicelib/core/resources.py

feat(api): fixed resources read time
feat(api): changed resources read time delta

v1.7.0 hot fixes

---

api/chalicelib/core/resources.py

Api v1.7.0 hotfix

---

ee/api/chalicelib/utils/SAML2_helper.py

feat(api): check forwarded SSO path

v1.7.0_hotfix

---

api/Dockerfile
api/Dockerfile.alerts
api/Dockerfile.alerts.dockerignore

feat(alerts): changed Dockerfile

v1.7.0 enhanced

---

api/chalicelib/core/resources.py
ee/api/chalicelib/core/resources.py

feat(chalice): fixed chalice get null-duration-session

v1.7.0 - hotfix

---

utilities/utils/helper.js

feat(assist): fixed sort by numeric attributes

v1.7.0 hotfix

---

api/chalicelib/core/assist.py
api/schemas.py
ee/utilities/package-lock.json
ee/utilities/utils/helper-ee.js
utilities/package-lock.json
utilities/utils/helper.js

feat(assist): support search operators
feat(chalice): support search operators for assist

enhanced assist

---

tracker/tracker-assist/src/Assist.ts

fix(tracker): fix assist typings

---

api/chalicelib/core/log_tool_elasticsearch.py
api/requirements-alerts.txt
api/requirements.txt
ee/api/requirements-alerts.txt
ee/api/requirements-crons.txt
ee/api/requirements.txt

feat(chalice): removed elasticsearch dependency

v1.7.0 ES change

---

api/chalicelib/core/log_tool_elasticsearch.py
api/requirements-alerts.txt
api/requirements.txt
ee/api/requirements-alerts.txt
ee/api/requirements-crons.txt
ee/api/requirements.txt

Reverts openreplay/openreplay#649

Revert "v1.7.0 ES change"

---

backend/pkg/url/method.go
ee/backend/pkg/db/clickhouse/connector.go

Added extra checks for urlMethod and resourceType in ClickHouse connector

Patch 1.8.0 (ClickHouse)

---

tracker/tracker-vuex/package.json
tracker/tracker-vuex/src/index.ts

Since #571 is abandoned, fixes are moved here
```js
const tracker = new Tracker( ... )
tracker.start()
```
Pinia:
```js
const authStore = useAuthStore()
const vuexPlugin = tracker.use(trackerVuex())
const authStorePlugin = vuexPlugin('authStore')
authStorePlugin(authStore)
```
Vuex:
```js
const vuexPlugin = tracker.use(trackerVuex())
const mainStorePlugin = vuexPlugin('mainStore')
const store = createStore({
state,
mutations,
plugins: [mainStorePlugin]
})
```

feat(tracker): capture pinia state updates

---

backend/cmd/ender/main.go
backend/internal/sessionender/ender.go
backend/pkg/log/queue.go
backend/pkg/messages/iterator.go

Process only Timestamp messages in ender's messageHandler to speed up the service in general

Speed up Ender

---

tracker/tracker/src/main/modules/input.ts

track type=tel inputs

---

api/chalicelib/utils/html/alert_notification.html

Due to some reason the previous pull didn't got updated.

Fixed year update in alertNotifi inside footer

---

api/chalicelib/core/autocomplete.py
api/chalicelib/core/countries.py
api/chalicelib/core/events.py
ee/api/.gitignore
ee/api/chalicelib/core/autocomplete_exp.py
ee/api/chalicelib/core/events.py
ee/api/chalicelib/core/sessions_metas.py
ee/api/chalicelib/utils/exp_ch_helper.py
ee/api/clean.sh

feat(chalice): refactored autocomplete
feat(chalice): fixed search for unexisting country
feat(chalice): fixed search for metadata with exp_autocomplete
feat(chalice): fixed search for errors with exp_autocomplete
feat(chalice): fixed search for errors with exp_autocomplete and no errors_mv
feat(chalice): created a new country

autocomplete changes 

---

backend/internal/http/router/handlers-web.go
backend/internal/http/router/router.go
backend/pkg/db/postgres/project.go
backend/pkg/db/types/project.go

We should add new column **beacon_size** to projects table

[HTTP] added custom project beacon size

---

frontend/app/assets/index.html

The service shouldn't be indexed by search engines.

= Do not expose OpenReplay to indexing

---

scripts/helmcharts/openreplay/files/dbops.sh

fix(migration): regression

---

scripts/helmcharts/init.sh

chore(init): Overwrite existing directory

---

api/build.sh
api/build_alerts.sh
backend/build.sh
frontend/build.sh
peers/build.sh
sourcemap-reader/build.sh
utilities/build.sh

```
PATCH=1 PUSH_IMAGE=1 DOCKER_REPO=public.ecr.aws/p1t3u8a3 bash -x build_deploy.sh
```
Will update the helm tag, and image tag

chore(build): Adding script to update helm tag

---

frontend/app/logger/index.js
frontend/app/player/web/messages/MFileReader.ts
tracker/tracker/src/main/app/index.ts
tracker/tracker/src/main/app/observer/iframe_observer.ts
tracker/tracker/src/main/app/observer/top_observer.ts
tracker/tracker/src/main/modules/network.ts

feat(tracker) capture network inside iframes

---

api/chalicelib/core/health.py
ee/api/chalicelib/core/health.py
scripts/helmcharts/openreplay/charts/chalice/templates/deployment.yaml

* chore(helm): Adding redis, kafka string env
* chore(chalice): Update health check endpoints
Fixes #1113
---------

Fix: chalice healthcheck namespace customization (#1118)

---

backend/cmd/db/main.go
backend/cmd/ender/main.go
backend/cmd/heuristics/main.go
backend/internal/config/common/config.go
backend/internal/db/service.go
backend/internal/heuristics/service.go
backend/pkg/memory/limit.go
backend/pkg/memory/manager.go

Checks memory consumption every second and pauses the consuming process (from Redis or Kafka) when the memory limit is reached.

Memory control manager

---

scripts/helmcharts/vars.yaml

chore(helm): Enabling redis string for helm template variable

---

scripts/helmcharts/openreplay-cli

fix(cli): Proper git tag propegation

---

scripts/helmcharts/openreplay-cli

So we'll have to upgrade OR only.

refactor(cli): In old clusters kyverno upgrade won't work.

---

tracker/tracker-mobx/README.md
tracker/tracker-mobx/package.json
tracker/tracker-mobx/src/index.ts
tracker/tracker-mobx/src/log.ts

since spy is noop in production, have to figure out a way to observe state changes. Current draft: using observe for state objects

fix(tracker): fix mobx plugin for prod builds

---

assist/Dockerfile
assist/package-lock.json
ee/assist/Dockerfile
ee/assist/package-lock.json
peers/Dockerfile
peers/package-lock.json
sourcemap-reader/Dockerfile
sourcemap-reader/package-lock.json
sourcemap-reader/package.json

fix(assist): use production environment
fix(peers): use production environment
fix(sourcemaps-reader): use production environment

v1.12.0 fixes

---

ee/scripts/schema/db/init_dbs/postgresql/1.10.0/1.10.0.sql
ee/scripts/schema/db/init_dbs/postgresql/1.11.0/1.11.0.sql
ee/scripts/schema/db/init_dbs/postgresql/1.12.0/1.12.0.sql
ee/scripts/schema/db/init_dbs/postgresql/1.5.0/1.5.0.sql
ee/scripts/schema/db/init_dbs/postgresql/1.5.1/1.5.1.sql
ee/scripts/schema/db/init_dbs/postgresql/1.5.2/1.5.2.sql
ee/scripts/schema/db/init_dbs/postgresql/1.5.3/1.5.3.sql
ee/scripts/schema/db/init_dbs/postgresql/1.5.4/1.5.4.sql
ee/scripts/schema/db/init_dbs/postgresql/1.6.0/1.6.0.sql
ee/scripts/schema/db/init_dbs/postgresql/1.7.0/1.7.0.sql
ee/scripts/schema/db/init_dbs/postgresql/1.8.0/1.8.0.sql
ee/scripts/schema/db/init_dbs/postgresql/1.8.1/1.8.1.sql
ee/scripts/schema/db/init_dbs/postgresql/1.9.0/1.9.0.sql
scripts/schema/db/init_dbs/postgresql/1.10.0/1.10.0.sql
scripts/schema/db/init_dbs/postgresql/1.11.0/1.11.0.sql
scripts/schema/db/init_dbs/postgresql/1.12.0/1.12.0.sql
scripts/schema/db/init_dbs/postgresql/1.5.0/1.5.0.sql
scripts/schema/db/init_dbs/postgresql/1.5.1/1.5.1.sql
scripts/schema/db/init_dbs/postgresql/1.5.2/1.5.2.sql
scripts/schema/db/init_dbs/postgresql/1.5.3/1.5.3.sql
scripts/schema/db/init_dbs/postgresql/1.5.4/1.5.4.sql
scripts/schema/db/init_dbs/postgresql/1.6.0/1.6.0.sql
scripts/schema/db/init_dbs/postgresql/1.7.0/1.7.0.sql
scripts/schema/db/init_dbs/postgresql/1.8.0/1.8.0.sql
scripts/schema/db/init_dbs/postgresql/1.8.1/1.8.1.sql
scripts/schema/db/init_dbs/postgresql/1.9.0/1.9.0.sql

* feat(DB): skip delta if wrong_version is detected without stopping global upgrade

feat(DB): skip delta version-exception

---

api/routers/core.py
api/routers/core_dynamic.py
api/routers/subs/health.py
api/routers/subs/metrics.py
api/routers/subs/v1_api.py
ee/api/chalicelib/utils/SAML2_helper.py
ee/api/entrypoint.sh
ee/api/requirements.txt
ee/api/routers/core_dynamic.py
ee/api/routers/ee.py
ee/api/routers/saml.py
ee/api/routers/subs/health.py
ee/api/routers/subs/metrics.py
ee/api/routers/subs/v1_api_ee.py

fix(chalice): EE support of multiworkers
refactor(chalice): cleaned SSO

fix(chalice): allow FastAPI to handel async automatically

---

backend/cmd/ender/main.go
backend/internal/db/datasaver/saver.go
backend/internal/sessionender/ender.go
backend/internal/sessionender/timecontroller.go
backend/pkg/db/types/error-event.go
backend/pkg/queue/types/types.go
backend/pkg/redisstream/consumer.go
ee/backend/pkg/db/redis/consumer.go
ee/backend/pkg/kafka/consumer.go

* feat(backend): new session end detection logic + several fixes
* feat(backend): support partitions managment in ender
* feat(backend): added new consumer support to redis
* feat(backend): added support for new consumer in kafka
* feat(backend): added new consumer support to redis (ee)
* feat(backend): small refactoring in ender

Ender logic update (#1435)

---

frontend/app/components/Assist/components/AssistActions/AssistActions.tsx
frontend/app/components/Session/LivePlayer.tsx
frontend/app/player/web/assist/Call.ts
frontend/app/player/web/assist/LocalStream.ts
frontend/app/utils/screenRecorder.ts

* fix(ui): merge audio tracks on node chain for recording
* fix(ui): merge audio tracks on node chain for recording
* fix(ui): fix

v1.14.0 patch (#1433)

---

scripts/helmcharts/openreplay/templates/job.yaml

1. if there are no version change
2. if skipMigration variable is set
3. if forceMigration variable is not set

refactor(helm): skip db migration, in conditions

---

scripts/helmcharts/openreplay/charts/alerts/templates/deployment.yaml
scripts/helmcharts/openreplay/charts/chalice/templates/deployment.yaml
scripts/helmcharts/openreplay/charts/utilities/templates/report-cron.yaml
scripts/helmcharts/openreplay/charts/utilities/templates/sessions-cleaner-cron.yaml
scripts/helmcharts/openreplay/charts/utilities/templates/telemetry-cron.yaml
scripts/helmcharts/openreplay/templates/_helpers.tpl

chore(helm): Create domain name with custom port

---

ee/assist/Dockerfile
ee/assist/servers/websocket.js

group connections with same peerId as error log.

assist: Enable error logging

---

ee/connectors/consumer_pool.py
ee/connectors/db/models.py
ee/connectors/db/utils.py
ee/connectors/utils/worker.py

fix(redshift-connector): Redshift connector update

---

scripts/docker-compose/install.sh

fix(install.sh): update typo

---

scripts/helmcharts/openreplay/templates/job.yaml
scripts/helmcharts/openreplay/values.yaml

Add affinity option to the migration job in helm chart

---

sourcemap-uploader/index.js

Fixes https://github.com/openreplay/openreplay/issues/1694

Do no log all soucemap contents when uploading it using the npm package method

---

frontend/app/components/Client/Integrations/Integrations.tsx

Addresses https://github.com/openreplay/openreplay/issues/1724.

fix(integrations): update ms teams subtitle to a real description

---

api/app.py
api/chalicelib/core/metadata.py
api/chalicelib/core/projects.py
api/chalicelib/core/sessions.py
api/chalicelib/core/users.py
api/routers/core_dynamic.py
api/routers/subs/health.py
api/routers/subs/v1_api.py
backend/internal/http/router/handlers-web.go
ee/api/chalicelib/core/projects.py
ee/api/chalicelib/core/sessions_exp.py
ee/api/chalicelib/core/users.py
ee/api/routers/core_dynamic.py

Reverts openreplay/openreplay#1701

Revert "chore(api): asyncify GET `/projects`, and propagate"

---

api/chalicelib/core/product_analytics.py
ee/api/chalicelib/core/product_analytics.py

fix(chalice): fixed Path Analysis support of contains/not-contains for exclude points

fix(chalice)

---

ee/scripts/schema/db/init_dbs/clickhouse/1.17.0/1.17.0.sql
ee/scripts/schema/db/init_dbs/postgresql/1.17.0/1.17.0.sql
ee/scripts/schema/db/init_dbs/postgresql/init_schema.sql
ee/scripts/schema/db/rollback_dbs/clickhouse/1.17.0/1.17.0.sql
ee/scripts/schema/db/rollback_dbs/postgresql/1.17.0/1.17.0.sql
scripts/schema/db/init_dbs/postgresql/1.17.0/1.17.0.sql
scripts/schema/db/init_dbs/postgresql/init_schema.sql
scripts/schema/db/rollback_dbs/postgresql/1.17.0/1.17.0.sql

* refactor(DB): Defined v1.17.0 delta scripts
* feat(DB): support of UT flag in sessions table

Api v1.17.0 (#1778)

---

api/requirements-alerts.txt
api/requirements.txt
ee/api/requirements-alerts.txt
ee/api/requirements-crons.txt
ee/api/requirements.txt

refactor(alerts): upgraded dependencies
refactor(chalice): upgraded dependencies

refactor(crons): upgraded dependencies

---

api/chalicelib/core/sessions.py
ee/api/chalicelib/core/sessions_exp.py

fix(chalice): fixed search sessions by specific issue in EXP mode

refactor(chalice): optimized search sessions by specific issue

---

api/app.py
ee/api/app.py

refactor(chalice): configurable AIO-PG pool size

fix(chalice): reduce AIO-PG pool size

---

frontend/app/components/Session/Player/ReplayPlayer/useShortcuts.ts

fix(ui): don't prevent default keyboard behavior unless its player shortcut

---

frontend/app/components/Session/LivePlayer.tsx
frontend/app/components/Session/Player/ReplayPlayer/PlayerContent.tsx
frontend/app/components/Session/WebPlayer.tsx
scripts/helmcharts/openreplay/charts/frontend/Chart.yaml

Updated patch build from main ae1a49fd917b8299316e9f9cb1f06daffbc462f6

---

scripts/helmcharts/openreplay/charts/chalice/Chart.yaml

Updated patch build from main f0488edf831f2061179eb7cf1b5b122cb48fbf8f

---

ee/api/requirements-alerts.txt
ee/api/requirements-crons.txt
ee/api/requirements.txt

refactor(chalice): removed python-multipart dependency

refactor(chalice): upgraded dependencies

---

scripts/helmcharts/openreplay/charts/chalice/Chart.yaml

Updated patch build from main e721ee6fc5b6b1b7424cd2dbe7fdd321cbaedf20

---

scripts/helmcharts/openreplay/charts/chalice/Chart.yaml

Updated patch build from main ff190e731559f49fdf008b2dc516e946d5c263e5

---

api/chalicelib/core/integration_jira_cloud.py

fix(chalice): fixed update JIRA integration
fix(chalice): fixed JIRA URL validation
fix(chalice): fixed add/update JIRA token

fix JIRA integration

---

api/chalicelib/core/sessions_replay.py
ee/api/.gitignore
ee/api/chalicelib/core/sessions_replay.py
ee/api/clean-dev.sh
ee/api/routers/core_dynamic.py

fix(chalice): support mobile changes in EE
fix(chalice): support first-mob in EE

refactor(chalice): refactored sessions_replay code

---

sourcemapreader/package-lock.json
sourcemapreader/package.json
sourcemapreader/servers/sourcemaps-handler.js

refactore(sourcemaps-reader): support AWS access role

refactore(sourcemaps-reader): upgraded dependencies

---

scripts/helmcharts/openreplay/charts/storage/Chart.yaml

Updated patch build from main 6f3a4405115591dfe769e89edaf0d4f493a5aaa3

---

scripts/helmcharts/openreplay/charts/chalice/Chart.yaml

Updated patch build from main 046e850a657e0790e9c8d3045d1400de84f62dc6

---

scripts/helmcharts/openreplay/charts/chalice/Chart.yaml

Updated patch build from main 11850cd27f89f9dbef32d4c3ec27feaeae1d93cd

---

scripts/helmcharts/openreplay/charts/chalice/Chart.yaml

Updated patch build from main 0295fb26cb63c868f3a32af006397c651397dcae

---

scripts/helmcharts/openreplay/charts/chalice/Chart.yaml

Updated patch build from main 21324125c73bd9b404231dba4d42e15cb86dae05

---

scripts/helmcharts/openreplay/charts/chalice/Chart.yaml

Updated patch build from main c3f07b5f051ae4f37ed2089bf16b4778effcce16

---

scripts/helmcharts/openreplay/charts/frontend/Chart.yaml

Updated patch build from main fe158e7ba5685c9b2830a21fbc7b67499d7996ca

---

api/chalicelib/core/significance.py
ee/api/schemas/schemas_ee.py

fix(chalice): fixed permissions

fix(chalice): fixed funnels

---

scripts/helmcharts/openreplay/charts/chalice/Chart.yaml

Updated patch build from main 5b5df8bf3264e8992184c4c6cd8e10f8744424b7

---

scripts/helmcharts/openreplay/charts/assist/Chart.yaml

Updated patch build from main 80af24f91ae1f3dbc8ee20ab39dd5329778e3a88

---

scripts/helmcharts/openreplay/charts/assist/Chart.yaml

Updated patch build from main a97b23a9a391c0ae78b003ca096b466fc0ce6aee

---

scripts/helmcharts/openreplay/charts/frontend/Chart.yaml

Updated patch build from main ec666fb23f876b96ef65847fae69755342ed68aa

---

scripts/helmcharts/openreplay/charts/frontend/Chart.yaml

Updated patch build from main 0edc130db019a030351c1e1010ba4b646f3af444

---

scripts/helmcharts/openreplay/charts/frontend/Chart.yaml

Updated patch build from main 0c24a9e8ccec7031cf3d806ef53f0b5933081d9d

---

scripts/helmcharts/openreplay/charts/frontend/Chart.yaml

Updated patch build from main 24922a4ab66728c20a443316bb9dc7bb93b56466

---

scripts/helmcharts/openreplay/charts/frontend/templates/ingress.yaml

fix: use values for ingressClassName

---

scripts/helmcharts/openreplay/charts/chalice/Chart.yaml

Updated patch build from main 6190a6b49567ee1d1872490569973370f2c3ca50

---

scripts/helmcharts/openreplay/charts/frontend/Chart.yaml

Updated patch build from main 409b05a24ca9cc68ea556246a8634dbbfa8eae2f

---

api/chalicelib/utils/email_handler.py

fix(chalice): fixed send multi-recipient email

---

scripts/helmcharts/openreplay/charts/chalice/Chart.yaml

Updated patch build from main 7cfaa0a49b84ee4fb691a67913146cb0eefbe84c

---

scripts/helmcharts/openreplay/charts/frontend/Chart.yaml

Updated patch build from main 644ef314251369c0e77f355cdb6ad8ea7f3462ff

---

scripts/helmcharts/openreplay/charts/frontend/Chart.yaml

Updated patch build from main f1c5231ff05b4df37baa00b342616c15d90b42dc

---

scripts/helmcharts/openreplay/charts/frontend/Chart.yaml

Updated patch build from main 30180b71592d1467fcb112119ebd8236dd6a20d5

---

ee/api/auth/auth_jwt.py
ee/api/schemas/schemas_ee.py
ee/scripts/schema/db/init_dbs/postgresql/1.18.0/1.18.0.sql

fix(chalice): permissions changes

fix(DB): permissions changes

---

scripts/helmcharts/openreplay/charts/frontend/Chart.yaml

Updated patch build from main 77fb1f0235dc820d20d689ae50f39b5811a8f67a

---

scripts/helmcharts/openreplay/charts/frontend/Chart.yaml

Updated patch build from main 0d514df1109cc7a8ebea4604ecd15eeb6ff12554

---

scripts/helmcharts/openreplay/charts/chalice/Chart.yaml

Updated patch build from main 72afae226b47e6ffc487338a96cf4c647cf021fe

---

scripts/helmcharts/openreplay/charts/frontend/Chart.yaml

Updated patch build from main c91881413a91bb4d2f096e662ddd4251325d2ff2

---

backend/internal/db/datasaver/saver.go
backend/pkg/db/postgres/events.go
backend/pkg/db/postgres/mobile.go
ee/backend/pkg/db/clickhouse/connector.go

* feat(spot): use float click coordinates instead of ints in PG
* feat(db): added support for float clicks in CH
* feat(db): fix float instead of uint8
* feat(mobile): new naming for mobile autocomplete types

Heatmaps fix (float coordinates) (#2403)

---

api/chalicelib/core/sessions.py
api/routers/core.py
api/schemas/schemas.py
ee/api/chalicelib/core/sessions_exp.py

fix(chalice): fixed autocomplete mobile sessions

fix(chalice): fixed search mobile sessions

---

spot/assets/mic-on-dark.svg
spot/assets/mic-on.svg
spot/entrypoints/content/Countdown.tsx
spot/entrypoints/content/RecordingControls.tsx
spot/entrypoints/content/SavingControls.tsx
spot/entrypoints/notifications.js
spot/entrypoints/popup/App.tsx
spot/entrypoints/popup/Settings.tsx
spot/package-lock.json
spot/yarn.lock

- Updated icons in mic settings
- Included prefix in Spot title
- Save recording notification has been updated
- Other minor UI improvements

Various improvements

---

frontend/app/components/Spots/SpotPlayer/components/SpotPlayerHeader.tsx
frontend/app/components/Spots/SpotsList/index.tsx
spot/entrypoints/content/Countdown.tsx

- Spot delete confirmation
- Spot comments UI update
- Minor copy updates

Minor fixes

---

scripts/helmcharts/openreplay/charts/frontend/Chart.yaml

Updated patch build from main a85d5196694c3880bec9eda51231b0d90e51df37

---

scripts/helmcharts/openreplay/charts/alerts/Chart.yaml

Updated patch build from main 347da4fb33325d2d46a2fd42f474dc31fe755416

---

scripts/helmcharts/openreplay/charts/frontend/Chart.yaml

Updated patch build from main e196643c8f7da00413933adff6ccf7b6a1ad3e04

---

scripts/helmcharts/openreplay/charts/frontend/Chart.yaml

Updated patch build from main 9ed207abb1fc0a0278c772261324dc1ecc2ef13b

---

scripts/helmcharts/openreplay/charts/spot/Chart.yaml

Updated patch build from main b89248067ade5baeff0dad2982cd1ed920c78b86

---

scripts/helmcharts/openreplay/charts/frontend/Chart.yaml

Updated patch build from main abe440f7290368ec233a1f33be5c08db4abd9adf

---

ee/api/requirements-alerts.txt
ee/api/requirements-crons.txt

fix(crons): fixed missing dependency for EE

fix(alerts): fixed missing dependency for EE

---

scripts/helmcharts/openreplay/charts/chalice/Chart.yaml

Updated patch build from main 018bf9c0be60a5f20fabeabbb0f15fec9abc91a4

---

scripts/helmcharts/openreplay/charts/frontend/Chart.yaml

Updated patch build from main 5cf584e8e1a4ef6679b2731c3520a5f49485698c

---

scripts/helmcharts/openreplay/charts/frontend/Chart.yaml

Updated patch build from main 93c605a28e1948484f56d49a12fff9429be490ac

---

scripts/helmcharts/openreplay/charts/alerts/Chart.yaml
scripts/helmcharts/openreplay/charts/chalice/Chart.yaml

Updated patch build from main 62ef3ca2dd804d4264cff5a02e9fedb50cae799c

---

scripts/helmcharts/openreplay/charts/frontend/Chart.yaml

Updated patch build from main 88a82acb8bbaf2b65b1a0f5681f1ab77b65084fc

---

scripts/helmcharts/openreplay/charts/frontend/Chart.yaml

Updated patch build from main 28a9b53d05bb888e61336e1ed3d5be61f93ff02a

---

scripts/helmcharts/openreplay/charts/frontend/Chart.yaml

Updated patch build from main 57b3044800aacb80035dfe3e65e4f207597a10ca

---

scripts/helmcharts/openreplay/charts/db/Chart.yaml

Updated patch build from main a56b94ba925f8891af8b70ca2e95b6b6c714a8ef

---

scripts/helmcharts/openreplay/charts/frontend/Chart.yaml

Updated patch build from main ffedeb491006dfe7d8f10298ac3b28b1208b0faa

---

scripts/helmcharts/openreplay/charts/chalice/Chart.yaml

Updated patch build from main 6802ddcd933b90a77c0861ff7e607e22c7821472

---

ee/backend/pkg/db/clickhouse/connector.go

This reverts commit a56b94ba925f8891af8b70ca2e95b6b6c714a8ef.

Revert "feat(clickhouse): added host/url to click events (#2680)"

---

scripts/helmcharts/openreplay/charts/db/Chart.yaml

Updated patch build from main 90d13c69aba23f3bc0072eebfe7542343015e8f0

---

api/chalicelib/core/heatmaps.py
api/schemas/schemas.py
ee/api/chalicelib/core/heatmaps.py

refactor(chalice): heatmap use path only

fix(chalice): heatmap handles null replay

---

scripts/helmcharts/openreplay/charts/chalice/Chart.yaml

Updated patch build from main 9eeaeaf4eb07a9d402ca11656d67577fd6ed288b

---

scripts/helmcharts/openreplay/charts/chalice/Chart.yaml

Updated patch build from main 5f144636e682fa71ec3a46e1d26aa52e1581662e

---

scripts/helmcharts/openreplay/charts/chalice/Chart.yaml

Updated patch build from main e729a6adac50cd019c2e7d2b6483c484bbff37e2

---

scripts/helmcharts/openreplay/charts/chalice/Chart.yaml

Updated patch build from main 16656d561833c2c7433ffd3d5ef7f2c96c812770

---

scripts/helmcharts/openreplay/charts/chalice/Chart.yaml

Updated patch build from main 8a99bcf7c82d900dbd4e1d150297a5121b05569e

---

scripts/helmcharts/openreplay/charts/chalice/Chart.yaml

Updated patch build from main 9ce67efb2629f23f40f124dde16aeaa34581bcb6

---

scripts/helmcharts/openreplay/charts/http/Chart.yaml

Updated patch build from main b2cb874a2a233d6d63410ce594687d395de7189d

---

scripts/helmcharts/openreplay/charts/alerts/Chart.yaml
scripts/helmcharts/openreplay/charts/chalice/Chart.yaml

Updated patch build from main 884f3499ef3d8fafafb9ac3cca07ffa6d9b58175

---

scripts/helmcharts/openreplay/charts/frontend/Chart.yaml

Updated patch build from main b080a987646833dd16283060dcb28c6fe9c7a6ce

---

tracker/tracker-assist/package.json

closes https://github.com/openreplay/openreplay/issues/2771

chore(peerDeps): fix @openreplay/tracker min version

---

scripts/helmcharts/openreplay/charts/frontend/Chart.yaml

Updated patch build from main f0e81002832bc13bdc8587773236c7ab65668f78

---

scripts/helmcharts/openreplay/charts/frontend/Chart.yaml

Updated patch build from main 1aa3b4b4e5ed5a55b71f8649fb5a9884389e4832

---

scripts/helmcharts/openreplay/charts/frontend/Chart.yaml

Updated patch build from main 332cbb35160100b3ff056d30aabfa1bfc33a1721

---

scripts/helmcharts/openreplay/charts/chalice/Chart.yaml

Updated patch build from main 2e5517509b6c677c326da319119ecc9b9c08a5bc

---

tracker/tracker/src/main/index.ts

Fixes: https://github.com/openreplay/openreplay/issues/2817

fix(tracker): prevent raising security error accessing window.top

---

scripts/helmcharts/openreplay/charts/frontend/Chart.yaml

Updated patch build from main 38594319f069605250c6ebf2a7d3c4770e9cc033

---

scripts/helmcharts/openreplay/charts/frontend/Chart.yaml

Updated patch build from main c66296a0501bdcdfb15e077d2cd6095a148b329e

---

scripts/helmcharts/openreplay/charts/frontend/Chart.yaml

Updated patch build from main 3484da2f605bc2cdea8c82464ac38fbb7454ceac

---

scripts/helmcharts/openreplay/charts/frontend/Chart.yaml

Updated patch build from main e54f62a0e6e6be2b09a936d04fd70a2466744d55

---

scripts/helmcharts/openreplay/charts/frontend/Chart.yaml

Updated patch build from main aa7b3fd617af9de89d8cc36e70ad4e6e0cf6161b

---

scripts/helmcharts/openreplay/charts/chalice/Chart.yaml

Updated patch build from main c8775f3c155deeccfecec4a053cfede5bb6b2ead

---

scripts/helmcharts/openreplay/charts/chalice/Chart.yaml

Updated patch build from main 77c084cac04ae5d749cb8f2db9524e189a9ece89

---

scripts/helmcharts/openreplay/charts/chalice/Chart.yaml

Updated patch build from main 1f16816252aa4a1086ffd75781185d077b597bdf

---

scripts/helmcharts/openreplay/charts/chalice/Chart.yaml

Updated patch build from main cceb4f0c250082c0523b55ff3ab4a64063048e50

---

scripts/helmcharts/openreplay/charts/chalice/Chart.yaml

Updated patch build from main 0417f2c75657f5b819359250c03f9103db66faa6

---

scripts/helmcharts/openreplay/charts/frontend/Chart.yaml

Updated patch build from main 262392f32ad14fdf7e16ff0d6cb0de095795fa5c

---

scripts/helmcharts/openreplay/charts/assets/Chart.yaml

Updated patch build from main 76b0ae7b0d782d3e817656b28fa1190b09b4c649

---

scripts/helmcharts/openreplay/charts/chalice/Chart.yaml
scripts/helmcharts/openreplay/charts/frontend/Chart.yaml

Updated patch build from main 8326b913f1403bf777c9b7aaa06ba82932a76797

---

frontend/app/components/Session/Player/ClipPlayer/ClipPlayerContent.tsx
frontend/app/components/Session_/EventsBlock/NoteEvent.tsx
frontend/app/components/Session_/Player/Controls/NotesList.tsx
frontend/app/components/Session_/Player/Controls/timeline.module.css

Highlighting timeline for better indication.

Highlight on timeline

---

scripts/helmcharts/openreplay/charts/frontend/Chart.yaml

Updated patch build from main 8914399cad318ca0f728cfe38fc7eae0cc5a8d21

---

api/chalicelib/utils/metrics_helper.py

refactor(chalice): throw an error when endTimestamp is 0 for product analytics

---

api/chalicelib/core/authorizers.py
api/chalicelib/core/spot.py
api/chalicelib/core/users.py
api/routers/subs/spot.py
ee/api/chalicelib/core/users.py
ee/api/routers/subs/spot.py

fix(chalice): fix spot multi-refresh token

fix(chalice): fix multi-refresh token fix(chalice): fix spot multi-refresh token

---

api/chalicelib/core/metrics/custom_metrics.py
api/routers/subs/metrics.py

fix(chalice): fixed search-product-analytics-cards

refactored(chalice): optimized search-product-analytics-cards fix(chalice): fixed search-product-analytics-cards

---

scripts/helmcharts/openreplay/charts/assist/Chart.yaml

Updated patch build from main ae95b487600971b056824c25defc530f60a20641

---

scripts/helmcharts/openreplay/charts/frontend/Chart.yaml

Updated patch build from main 4c159b2d26be7baf2cab739dba27590f4de23c40

---

frontend/app/components/ForgotPassword/CreatePassword.tsx
frontend/app/components/ForgotPassword/ResetPasswordRequest.tsx

The token validation checks were redundant as the validation is already handled by the captcha wrapper component. This change simplifies the password reset flow while maintaining security.

fix(auth): remove unnecessary captcha token validation

---

frontend/app/components/Session_/GraphQL/GraphQL.tsx

Fixes: https://github.com/openreplay/openreplay/issues/3199

fix(GraphQL): remove unused useTranslation hook

---

scripts/helmcharts/openreplay/charts/frontend/Chart.yaml

Updated patch build from main c77b0cc4deb8adfbd6b3f92e0e9d5b0416524bb1

---

scripts/helmcharts/openreplay/charts/frontend/Chart.yaml

Updated patch build from main fd12cc758511cdc28e588f1800967044838f0da2

---

scripts/helmcharts/openreplay/charts/frontend/Chart.yaml

Updated patch build from main 1e2bd19d3218747631f104bd5094c5da8be6ae7a

---

scripts/helmcharts/openreplay/charts/frontend/Chart.yaml

Updated patch build from main 9f693f220d9b25f43f2a797daf2c20d5e3bba99a

---

scripts/helmcharts/openreplay/templates/job.yaml

fix(init): remove duplicate clone

---

scripts/helmcharts/openreplay/charts/assist/Chart.yaml
scripts/helmcharts/openreplay/charts/frontend/Chart.yaml

Updated patch build from main 214be95ecc09ef252ca41dcf47acf8b050d958fe

---

scripts/helmcharts/openreplay/charts/frontend/Chart.yaml

Updated patch build from main c0a47340543f41208881a4be3b0da2a216b3e8c7

---

scripts/helmcharts/openreplay/charts/frontend/Chart.yaml

Updated patch build from main 6b35df7125cd89cab62c0d79e5fa12f558fa096c

---

scripts/helmcharts/openreplay/charts/chalice/Chart.yaml

Updated patch build from main 5d514ddaf2e22f13389ac4375a94344d8bad299d

---

scripts/helmcharts/openreplay/charts/frontend/Chart.yaml

Updated patch build from main b0e7054f89af92f4beaeaad9d140efca7dc9a638

---

.github/workflows/patch-build-old.yaml

chore(ci): tag patching

---

.github/workflows/patch-build-old.yaml

- **ci(action): Build and patch github tags**

or 1885 support old patch build from github actions

---

.github/workflows/patch-build-old.yaml

chore(action): cloning specific tag

---

scripts/helmcharts/openreplay/charts/frontend/Chart.yaml

Reverts openreplay/openreplay#3282

Revert "Updated patch build from main 6777d5ce2a1f283a746d4ab9be7d0614ca0dd0e4"

---

scripts/helmcharts/openreplay/charts/frontend/Chart.yaml

Updated patch build from main f6ae5aba888d2f15b1b8f6c1a9d42e2f773ff404

---

frontend/app/components/Dashboard/components/WidgetSessions/WidgetSessions.tsx

- Refactored session filtering logic to handle nested filters properly.
- Enhanced `fetchSessions` to ensure null checks and avoid errors.
- Updated `loadData` to handle `USER_PATH` and `HEATMAP` metric types.
- Improved UI consistency by adjusting spacing and formatting.
- Replaced redundant code with cleaner, more maintainable patterns.
This change improves the reliability and readability of the session filtering and loading logic in the WidgetSessions component.

feat(widget-sessions): improve session filtering logic

---

scripts/helmcharts/openreplay/charts/frontend/Chart.yaml

Updated patch build from main 30ce37896c99d55303067f5046497570197dcda5

---

frontend/app/components/Session_/Subheader.tsx
frontend/app/components/Session_/WarnBadge.tsx
frontend/app/components/shared/FetchDetailsModal/components/FetchTabs/FetchTimings.tsx
frontend/devbox.json
frontend/devbox.lock

- Request Timings UI is mapped to Chrome FETCH request timing UI
- The notification banner has been updated (position and style). so it doesn't overlap on Network Panel drawer.

Request Timings UI update

---

scripts/helmcharts/openreplay/charts/frontend/Chart.yaml

Updated patch build from main 5070ded1f42d7d25897bf317afb7381f3dff9df8

---

scripts/helmcharts/openreplay/charts/frontend/Chart.yaml

Updated patch build from main 13dbb60d8b94c2ae75bea1cde985a402c91b14f8

---

scripts/docker-compose/docker-compose.yaml
scripts/docker-compose/hacks/tpls/docker-compose.tpl

fix(docker-compose): proper volume path #3279

---

scripts/helmcharts/openreplay/charts/frontend/Chart.yaml

Updated patch build from main 9ed3cb1b7edae196dfdcc5ad8e90fb35895cf02d

---

scripts/helmcharts/openreplay/charts/frontend/Chart.yaml

Updated patch build from main f4d5b3c06e8ecdb8881357beb4b1cc7688c40f3a

---

scripts/helmcharts/openreplay/charts/frontend/Chart.yaml

Updated patch build from main 9bdf6e4f9295f2347543474cd828561d689e22b0

---

.github/workflows/update-tag.yaml

ci(actions): Auto update tag for patch build

---

scripts/helmcharts/openreplay/charts/frontend/Chart.yaml

Updated patch build from main ccb332c6367fc240bee3801c89f95fe7da2b5700

---

.github/workflows/update-tag.yaml

ci(actions): fix push denied (#3392) (#3393)

---

scripts/helmcharts/openreplay/charts/frontend/Chart.yaml

Updated patch build from main 66b485cccffa3b9d93e4f432effac8a2ff3d171b

---

scripts/helmcharts/openreplay/charts/chalice/Chart.yaml

Updated patch build from main 71b7cca5697d74024c2643a3722784858f60a0be

---

scripts/helmcharts/openreplay/charts/frontend/Chart.yaml

Updated patch build from main 930417aab46e88b4a9149df4959eafadca08ac8e

---

.github/workflows/patch-build-old.yaml

feat(ci): Support building from branch for old patch

---

.github/workflows/patch-build.yaml

- **chore(build): Better error handling**
- **fix(build): remove fetch depth, as it might cause issue in rebase**
- **fix(build): proper platform**

actions fix or 2070

---

frontend/app/components/Dashboard/components/WidgetView/WidgetView.tsx

Reverts openreplay/openreplay#3450

Revert "fix(ui): new card data state is not updating"

---

api/routers/subs/metrics.py
api/schemas/schemas.py

refactor(chalice): removed endpoint to force UI to use the correct one

refactor(chalice): changed dashboard-card's payload refactor(chalice): removed endpoint to force UI to use the correct one

---

scripts/helmcharts/openreplay/charts/frontend/Chart.yaml

Updated patch build from main 36abcda1e1201edd01a5353f55c474b837dea747

---

.github/workflows/patch-build.yaml

fix(actions): frontend image with proper tag

---

scripts/helmcharts/openreplay/charts/chalice/Chart.yaml

Updated patch build from main 53aa4bc12a1288008866fe136b4269fd60789507

---

scripts/helmcharts/databases/charts/clickhouse/values.yaml

chore(clickhouse): reduce override config file priority

---

scripts/helmcharts/openreplay/charts/chalice/Chart.yaml

Updated patch build from main 052c0814d5e65b9f72930a006d681d391706afc7

---

scripts/helmcharts/openreplay/charts/frontend/Chart.yaml

Updated patch build from main 3bd83f9235f31685d52b2ef9578f6e24cda71cf6

---

scripts/helmcharts/openreplay/charts/frontend/Chart.yaml

Updated patch build from main 671c768b77700eb8c5c0c556f584cac333fcca37

---

scripts/helmcharts/openreplay/charts/frontend/Chart.yaml

Updated patch build from main 805aa061fcebeeaa7011889797c22135771db0ba

---

scripts/helmcharts/openreplay/charts/ender/Chart.yaml

Updated patch build from main 78a02c4555c10a88cba8664e9165566862a64bfa

---

api/Pipfile
api/chalicelib/core/product_analytics/filters.py
api/chalicelib/core/product_analytics/properties.py
api/requirements-alerts.txt
api/requirements.txt
ee/api/Pipfile
ee/api/requirements-alerts.txt
ee/api/requirements-crons.txt
ee/api/requirements.txt

refactor(chalice): Event's filters categories
refactor(chalice): Event's default filters

refactor(chalice): upgraded dependencies refactor(chalice): Event's filters categories refactor(chalice): Event's default filters

---

backend/pkg/analytics/model/model.go
backend/pkg/analytics/search/search.go

refactor(gapi): validate session's search payload

fix(gapi): fixed product analytics drilldown refactor(gapi): validate session's search payload
