scripts/helm/app/alerts.yaml
scripts/helm/app/assets.yaml
scripts/helm/app/chalice.yaml
scripts/helm/app/db.yaml
scripts/helm/app/ender.yaml
scripts/helm/app/http.yaml
scripts/helm/app/integrations.yaml
scripts/helm/app/sink.yaml
scripts/helm/app/storage.yaml
scripts/helm/install.sh
scripts/helm/kube-install.sh
scripts/helm/nginx-ingress/nginx-ingress/templates/configmap.yaml
scripts/helm/nginx-ingress/nginx-ingress/values.yaml
scripts/helm/roles/openreplay/tasks/install-apps.yaml
scripts/helm/roles/openreplay/tasks/pre-check.yaml
scripts/helm/roles/openreplay/templates/monitoring.yaml
scripts/helm/vars.yaml

Kubernetes cluster and workloads will be monitored for the enterprise edition.
```
./install.sh -e <enterprise_key> --monitoring
```
Dashboards should be available in `https://domain_name/grafana`
Username: admin
Password can be specified else autogenerated. In case of later, the password will be updated in `vars.yaml`.

Monitoring support for enterprise edition

---

scripts/helm/local_run.md

Instructions for change the code and deploy it to your own open replay instance, without needing a docker repository.

feat(install): build and run images locally.

---

scripts/helm/migration.yaml
scripts/helm/roles/openreplay/tasks/main.yml
scripts/helm/upgrade.sh
scripts/helm/vars_template.yaml

We've to do upgrade release on release rather than fresh installation.
This script will migrate the data and upgrade the applications.
HowTo:
- copy the current openreplay folder to `_version-number`.
`cp -rf openreplay openreplay-v1.1.0`
- Clone the new OpenReplay version
`git clone https://github.com/openreplay/openreplay -b v1.2.0`
- If you've done any manual changes, like application variable updation, change it in the new version folder.
`vim openreplay/scripts/helm/apps/<app>.yaml`
- Upgrade
```
cd openreplay/scripts/helm
bash upgrade.sh /home/ubuntu/openreplay-v1.1.0
```
TODO:
- Preserve custom configurations from user, like postgres cpu changes
As of now, the manual overrides to the app configs, will be reset. So if you have any custom overrides,
prior to run the upgrade scripts, …

Feature: Upgrade script

---

scripts/helm/roles/openreplay/templates/clickhouse.yaml
scripts/helm/roles/openreplay/templates/postgresql.yaml
scripts/helm/roles/openreplay/templates/redis.yaml
scripts/helm/vars.yaml

If you need to override the default resource allocation or dbs, which is
indented to be for small machines, you can override the default
allocation here.
Ref: https://github.com/openreplay/openreplay/issues/64

feat(install): override default db resource allocation

---

frontend/app/player/MessageDistributor/managers/AssistManager.ts

- Changed URL().host to URL().hostname so it wont attached port while the config set again another port and causing duplicate port when connect using peerjs.
- Changed the port in the config to check first if the URL() has port defined, then using the defined port first, so user can use custom port number for ws, when there is no custom port defined at the domainUrl, then it will then check https or not and append the correct port.

Changed how the _config in AssistManager construct

---

scripts/helmcharts/openreplay/charts/assets/templates/deployment.yaml
scripts/helmcharts/openreplay/charts/http/templates/deployment.yaml

We need to check what is the object store endpoint.
There can be 4 options
1. Using minio inside kube clster
2. Using minio managed external cluster, like aws minio offering
3. Using GCP or other object stores compatible with s3 apis
4. Using AWS itself.
AWS uses bucketname.endpoint/object while others use endpoint/bucketname/object

chore(helm): S3 endpoint validation

---

scripts/helmcharts/init.sh

This will help to install OpenReplay against the Kubernetes cluster using
`SKIP_K8S_INSTALL=true SKIP_K8S_TOOLS=true DOMAIN_NAME=openreplay.local bash init.sh`
> You should have a proper KUBECONFIG env variable set.

Openreplay install, without kubernetes and related tools

---

backend/pkg/db/postgres/messages-common.go
backend/services/db/messages.go

Hotfix for db component to store metadata directly to db, instead of collecting in batches.

feat(backend/db): send metadata directly to db (removed from batches)

---

tracker/tracker/package.json
tracker/tracker/src/main/app/index.ts
tracker/tracker/src/main/app/nodes.ts
tracker/tracker/src/main/app/observer/observer.ts
tracker/tracker/src/main/modules/scroll.ts

* use of `.nodeType` property instead of `instanceof` when possible
* use of `.nodeName` property instead of `instanceof` for Elements 
* 2 previous also solve issue of non-function `instanceof` under different iframe contexts
* use map instead of array for storing recent nodes
* check node scrolls on start only

Tracker pf fix

---

frontend/nginx.conf

Currently all urls except the index are not getting served the react files in order to view them after a page reload. This breaks "back " navigations and page refreshing.
Example:
/login

fix(ui): Serve react index file for all page urls

---

tracker/tracker-assist/src/Assist.ts

If the client abruptly ends the tracker instance, the Assist session is not cleaned up properly, which leaves the Assist agent's cursor on the screen.

change(tracker): Ensure that the remote control session is ended in the case that the tracker instance is cleaned

---

sourcemap-uploader/cli.js

The arg was changed to be `--logs` instead of `--verbose`, but this change is needed to actually use the value and print verbose output with `-l`.

Fix verbose CLI option

---

tracker/tracker/src/main/app/index.ts
tracker/tracker/src/main/index.ts

This PR is the implementation of this Q&A https://github.com/openreplay/openreplay/discussions/862
Added optional option to `getSessionURL`:
```ts
getSessionURL(options?: { jumpToCurrentTime?: boolean })
```
Example of the result:
https://app.openreplay.com/1234/session/123456789?jumpto=4432

feat(tracker): add option to jump to current time in `getSessionURL`

---

backend/cmd/assets/main.go
backend/cmd/db/main.go
backend/cmd/ender/main.go
backend/cmd/heuristics/main.go
backend/cmd/http/main.go
backend/cmd/integrations/main.go
backend/cmd/sink/main.go
backend/cmd/storage/main.go
backend/internal/config/assets/config.go
backend/internal/config/db/config.go
backend/internal/config/ender/config.go
backend/internal/config/heuristics/config.go
backend/internal/config/http/config.go
backend/internal/config/integrations/config.go
backend/internal/config/sink/config.go
backend/internal/config/storage/config.go

Now we can use PROFILER_ENABLED variable to enable golang pprof. It's disabled by default

Added env variable for enabling pprof

---

ee/backend/pkg/db/clickhouse/connector.go

Fixed a panic when casting the 'webError' source value to uint8 (on batch insert method)

[CH] Batch insert panic fix

---

scripts/helmcharts/openreplay/values.yaml

Without this flag, if the helm version is older, then we'll get
template error.

chore(helm): Adding tls enabled to redis

---

tracker/tracker/src/webworker/index.ts

The webworker has a bug where after being foregrounded (on mobile especially), if the writer or sender is not present, it will throw an error which will bubble up and crash the entire app. Instead, log a debug message and allow the writer / sender to reinit

change(tracker): webworker crash fix due to uninitialised sender/writer

---

scripts/helmcharts/openreplay/charts/utilities/templates/efs-cron.yaml
scripts/helmcharts/openreplay/charts/utilities/values.yaml

The openreplay chart is currently uninstallable due to this error:
```
Error  error   11s (x5 over 28s)  helm-controller  Helm install failed: error while running post render on files: map[string]interface {}(nil): yaml: unmarshal errors:
line 44: mapping key "restartPolicy" already defined at line 22
```
This fixes this issue so the chart can be installed.

Fix invalid yaml errors in openreplay chart

---

scripts/helmcharts/openreplay-cli

CLI Now support
1. `openreplay -e` -> Opens the config file, and after change, reloads the installation.
2. `openreplay -i openreplay.mydomain.com` -> Installs OpenReplay
3. `openreplay -c 14` -> Deletes data older than 14 days from OR instance

CLI improvements

---

scripts/helmcharts/openreplay/charts/quickwit/templates/deployment.yaml

Helm templating currently fails due to a stray `{{- end}}` tag. The issue was introduced here: [scripts/helmcharts/openreplay/charts/quickwit/templates/deployment.yaml](https://github.com/openreplay/openreplay/pull/836/files#diff-06845d64fe4d60dd0e9a7ef5d81eab86f0101dae5b43f1f083e72d04b9f9390e)

feat(helm): fix quickwit deployment

---

ee/recommendation/ml_trainer/requirements.txt

There are 1 security vulnerabilities found in apache-airflow 2.6.1
- [CVE-2023-35005](https://www.oscs1024.com/hd/CVE-2023-35005)
Upgrade apache-airflow from 2.6.1 to 2.6.2 for vulnerability fix
Ideally, no insecure libs should be used.
By using the [GitHub Actions](https://github.com/murphysecurity/actions) configurations provided by murphysec, we can conduct automatic code security checks in our CI pipeline.
[PR Specification](https://www.oscs1024.com/docs/pr-specification/) from OSCS

fix(sec): upgrade apache-airflow to 2.6.2

---

ee/recommendation/ml_trainer/requirements.txt

There are 1 security vulnerabilities found in apache-airflow 2.6.2
- [CVE-2023-35908](https://www.oscs1024.com/hd/CVE-2023-35908)
Upgrade apache-airflow from 2.6.2 to 2.7.1 for vulnerability fix
Ideally, no insecure libs should be used.
By using the [GitHub Actions](https://github.com/murphysecurity/actions) configurations provided by murphysec, we can conduct automatic code security checks in our CI pipeline.
[PR Specification](https://www.oscs1024.com/docs/pr-specification/) from OSCS

fix(sec): upgrade apache-airflow to 2.7.1

---

api/NOTES.md
api/app.py
api/chalicelib/core/signup.py
api/chalicelib/core/tenants.py
api/orpy.py
api/requirements.txt
api/routers/core_dynamic.py
api/routers/subs/health.py
ee/api/chalicelib/core/signup.py
ee/api/chalicelib/core/tenants.py
ee/api/requirements.txt
ee/api/routers/core_dynamic.py
ee/api/routers/subs/health.py

- Add async database pooler from psycopg3 aka `psycopg`
- Make it available through a global available at runtime as `orpy.get().database`
And make async `chalice.core.tenants.tenants_exists` and all functions depending on it. Keep around the synchronous version to be able to call it at top-level, and exclude some routes after a restart of the application server for security reasons.

chore(api): asyncify `chalice.core.tenants.tenants_exists`, and propagate

---

ee/api/chalicelib/core/sessions_exp.py

fix(chalice): fixed sessions search with not-contains operator for 1 single events filter

fix(chalice) v1.15.0

---

ee/api/entrypoint.sh

Even if FastAPI routes are synchronous, FastAPI rely on ASGI.
Revert "feat(api): use the default sync worker class, and only one worker."
This reverts commit 39ca414137b60885c1a439e0cae03290009199c7.

fix(api): fastapi requires uvicorn workers in gunicorn

---

scripts/helmcharts/databases/Chart.yaml

There was a duplicate entry for minio in the database chart's Chart.yaml file that prevents it from being deployed using helm upgrade like the Kubernetes deployment guide says it should.

removed duplicate dependency entry 🙂🙂

---

frontend/app/components/Dashboard/components/MetricsList/MetricsList.tsx

Change the filter type comparison from checking against 'all' to checking against an empty string. This ensures proper filtering behavior when filtering metrics in the dashboard component.

fix(dashboard): update filter condition in MetricsList

---

frontend/app/components/Login/SSOLogin.tsx
frontend/app/mstore/userStore.ts

Add dedicated isSSOSupported property to correctly identify when SSO authentication is available, properly handling the 'msaas' edition case separately from enterprise edition checks. This fixes SSO visibility in the login interface.

refactor(auth): separate SSO support from enterprise edition

---

.github/workflows/patch-build-old.yaml

feat(workflow): update commit timestamp for patching
Add a step to set the commit timestamp of the HEAD commit to be 1
second newer than the oldest of the last 3 commits. This ensures
proper chronological order while preserving the commit content.
- Fetch deeper history to access commit history
- Get oldest timestamp from recent commits
- Set new commit date with BSD-compatible date command
- Verify timestamp change with git log
The workflow was previously checking out 'main' branch with a
comment indicating it needed to be fixed. This change makes it
properly checkout the tag specified by the workflow input.

ci(action): Build and patch github tags

---

frontend/app/components/Dashboard/components/WidgetWrapper/WidgetWrapperNew.tsx
frontend/app/mstore/dashboardStore.ts

Change default drill down period from LAST_7_DAYS to LAST_24_HOURS and preserve current period when drilling down on chart click

feat(dashboard): set initial drill down period

---

frontend/app/components/Dashboard/Widgets/CustomMetricsWidgets/SessionsBy.tsx

Added a conditional check to handle the FETCH metric in the SessionsBy component. When the metric is FETCH, a specific filter with key FETCH_URL, operator is, and value derived from data.name is applied. This ensures proper filtering behavior for FETCH-related metrics.

feat(SessionsBy): add specific filter for FETCH metric

---

scripts/helmcharts/databases/charts/clickhouse/templates/statefulset.yaml
scripts/helmcharts/databases/charts/clickhouse/values.yaml

Properly mount clickhouse user configuration files to the users.d
directory with correct paths for each file. Also adds several
performance-related settings to the default user profile including
query cache and JSON type support.

fix(clickhouse): update user config mount paths

---

.github/workflows/patch-build-old.yaml

Remove the -b flag from git checkout command as the branch already
exists and we just need to switch to it, not create it.

fix: remove -b flag from git checkout in patch workflow

---

.github/workflows/patch-build-old.yaml

without the complete history, the git checkout will fail

fix: fetch entire git history

---

scripts/helmcharts/openreplay/templates/job.yaml

If minio is enabled and an existing secret is used for s3 access, the migration job is created with wrong credentials or fails when `Values.minio.globals.minio.` isn't configured.

fix(minio): Support existing secret on minio migration job

---

scripts/helmcharts/databases/charts/redis/templates/redis-master-statefulset.yaml

Add a preStart lifecycle hook to the Redis master StatefulSet. This hook runs
`redis-check-aof --fix` on all incremental AOF files before the Redis server
starts, ensuring any corrupted AOF files are fixed automatically. This helps
improve data integrity and startup reliability.

feat(redis): add preStart hook to fix AOF files on startup (#3612)

---

.github/workflows/patch-build.yaml

Update managed build logic to ensure backend services like "ender" are built for both amd64 and arm64 architectures. Refactor case statement to use correct build arguments and script context, enabling ARM image builds for all services.

fix(patch-build): build ARM images for backend services

---

scripts/helmcharts/databases/charts/redis/templates/redis-master-statefulset.yaml

Refactor the postStart lifecycle hook to first check and fix the main
appendonly.aof file if it exists, then iterate and fix any incremental
AOF files. This ensures both the main and incremental AOF files are
properly recovered, reducing the risk of data loss or startup issues
due to corrupted AOF files.

fix(redis): improve AOF file recovery logic on startup
